[theme]

base="dark"
# Primary accent for interactive elements
primaryColor = '#F50033'

# Background color for the main content area
backgroundColor = '#000000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#000000'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"


